version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - 'database_data:/var/lib/postgresql/data'
      - './sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql'
volumes:
  database_data:
    driver: local
