--------------------------------Populate m_state------------------------------------------


INSERT INTO m_state(id, state_name, country) values (1, 'Andaman and Nicobar (UT)', 'IN');
INSERT INTO m_state(id, state_name, country) values (2, 'Andhra Pradesh', 'IN');
INSERT INTO m_state(id, state_name, country) values (3, 'Arunachal Pradesh', 'IN');
INSERT INTO m_state(id, state_name, country) values (4, 'Assam', 'IN');
INSERT INTO m_state(id, state_name, country) values (5, 'Bihar', 'IN');
INSERT INTO m_state(id, state_name, country) values (6, 'Chandigarh (UT)', 'IN');
INSERT INTO m_state(id, state_name, country) values (7, 'Chhattisgarh', 'IN');
INSERT INTO m_state(id, state_name, country) values (8, 'Dadra and Nagar Haveli and Daman and Diu (UT)', 'IN');
INSERT INTO m_state(id, state_name, country) values (9, 'Ladakh (UT)', 'IN');
INSERT INTO m_state(id, state_name, country) values (10, 'Delhi (UT)', 'IN');
INSERT INTO m_state(id, state_name, country) values (11, 'Goa', 'IN');
INSERT INTO m_state(id, state_name, country) values (12, 'Gujarat', 'IN');
INSERT INTO m_state(id, state_name, country) values (13, 'Haryana', 'IN');
INSERT INTO m_state(id, state_name, country) values (14, 'Himachal Pradesh', 'IN');
INSERT INTO m_state(id, state_name, country) values (15, 'Jammu and Kashmir (UT)', 'IN');
INSERT INTO m_state(id, state_name, country) values (16, 'Jharkhand', 'IN');
INSERT INTO m_state(id, state_name, country) values (17, 'Karnataka', 'IN');
INSERT INTO m_state(id, state_name, country) values (18, 'Kerala', 'IN');
INSERT INTO m_state(id, state_name, country) values (19, 'Lakshadweep (UT)', 'IN');
INSERT INTO m_state(id, state_name, country) values (20, 'Madhya Pradesh', 'IN');
INSERT INTO m_state(id, state_name, country) values (21, 'Maharashtra', 'IN');
INSERT INTO m_state(id, state_name, country) values (22, 'Manipur', 'IN');
INSERT INTO m_state(id, state_name, country) values (23, 'Meghalaya', 'IN');
INSERT INTO m_state(id, state_name, country) values (24, 'Mizoram', 'IN');
INSERT INTO m_state(id, state_name, country) values (25, 'Nagaland', 'IN');
INSERT INTO m_state(id, state_name, country) values (26, 'Orissa', 'IN');
INSERT INTO m_state(id, state_name, country) values (27, 'Puducherry (UT)', 'IN');
INSERT INTO m_state(id, state_name, country) values (28, 'Punjab', 'IN');
INSERT INTO m_state(id, state_name, country) values (29, 'Rajasthan', 'IN');
INSERT INTO m_state(id, state_name, country) values (30, 'Sikkim', 'IN');
INSERT INTO m_state(id, state_name, country) values (31, 'Tamil Nadu', 'IN');
INSERT INTO m_state(id, state_name, country) values (32, 'Telangana', 'IN');
INSERT INTO m_state(id, state_name, country) values (33, 'Tripura', 'IN');
INSERT INTO m_state(id, state_name, country) values (34, 'Uttar Pradesh', 'IN');
INSERT INTO m_state(id, state_name, country) values (35, 'Uttarakhand', 'IN');
INSERT INTO m_state(id, state_name, country) values (36, 'West Bengal', 'IN');



--------------------------------Populate m_village------------------------------------------


INSERT INTO m_village(id, village_name, state_id) values (1,'Aali',10);
INSERT INTO m_village(id, village_name, state_id) values (2,'Akbar Pur Majra',10);
INSERT INTO m_village(id, village_name, state_id) values (3,'Ali Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (4,'Asalat Pur Khawad',10);
INSERT INTO m_village(id, village_name, state_id) values (5,'Asola',10);
INSERT INTO m_village(id, village_name, state_id) values (6,'Aya Nagar',10);
INSERT INTO m_village(id, village_name, state_id) values (7,'Badar Pur Khadar',10);
INSERT INTO m_village(id, village_name, state_id) values (8,'Badar Pur Majra Burari',10);
INSERT INTO m_village(id, village_name, state_id) values (9,'Badhosra',10);
INSERT INTO m_village(id, village_name, state_id) values (10,'Bakhtawar Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (11,'Bakkar Wala',10);
INSERT INTO m_village(id, village_name, state_id) values (12,'Bankauli',10);
INSERT INTO m_village(id, village_name, state_id) values (13,'Bankner',10);
INSERT INTO m_village(id, village_name, state_id) values (14,'Baqar Garh',10);
INSERT INTO m_village(id, village_name, state_id) values (15,'Baqiabad',10);
INSERT INTO m_village(id, village_name, state_id) values (16,'Barwala',10);
INSERT INTO m_village(id, village_name, state_id) values (17,'Bawana',10);
INSERT INTO m_village(id, village_name, state_id) values (18,'Bazid Pur Thakran',10);
INSERT INTO m_village(id, village_name, state_id) values (19,'Begum Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (20,'Bhalswa Jahangir Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (21,'Bhati',10);
INSERT INTO m_village(id, village_name, state_id) values (22,'Bhor Garh',10);
INSERT INTO m_village(id, village_name, state_id) values (23,'Bihari Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (24,'Bodh Pur Bija Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (25,'Budhan Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (26,'Chand Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (27,'Chandan Hola',10);
INSERT INTO m_village(id, village_name, state_id) values (28,'Chatesar',10);
INSERT INTO m_village(id, village_name, state_id) values (29,'Chattar Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (30,'Chhawala',10);
INSERT INTO m_village(id, village_name, state_id) values (31,'Chilla Saroda Bangar',10);
INSERT INTO m_village(id, village_name, state_id) values (32,'Chilla Saroda Khadar',10);
INSERT INTO m_village(id, village_name, state_id) values (33,'Dallo Pura',10);
INSERT INTO m_village(id, village_name, state_id) values (34,'Darya Pur Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (35,'Darya Pur Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (36,'Daulat Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (37,'Delhi Cantt.',10);
INSERT INTO m_village(id, village_name, state_id) values (38,'Deoli',10);
INSERT INTO m_village(id, village_name, state_id) values (39,'Deorala',10);
INSERT INTO m_village(id, village_name, state_id) values (40,'Dera',10);
INSERT INTO m_village(id, village_name, state_id) values (41,'Dhansa',10);
INSERT INTO m_village(id, village_name, state_id) values (42,'Dichaon Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (43,'Dindar Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (44,'DMC',10);
INSERT INTO m_village(id, village_name, state_id) values (45,'Fateh Pur Beri',10);
INSERT INTO m_village(id, village_name, state_id) values (46,'Fateh Pur Jat',10);
INSERT INTO m_village(id, village_name, state_id) values (47,'Gadai Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (48,'Garhi Khasru',10);
INSERT INTO m_village(id, village_name, state_id) values (49,'Garhi Mendu',10);
INSERT INTO m_village(id, village_name, state_id) values (50,'Garhi Rindhala',10);
INSERT INTO m_village(id, village_name, state_id) values (51,'Ghalib Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (52,'Gharoli',10);
INSERT INTO m_village(id, village_name, state_id) values (53,'Gharonda Neemka Bangar alias Patpar Ganj',10);
INSERT INTO m_village(id, village_name, state_id) values (54,'Gheora',10);
INSERT INTO m_village(id, village_name, state_id) values (55,'Ghitorni',10);
INSERT INTO m_village(id, village_name, state_id) values (56,'Ghoga',10);
INSERT INTO m_village(id, village_name, state_id) values (57,'Goela Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (58,'Goman Hera',10);
INSERT INTO m_village(id, village_name, state_id) values (59,'Hamid Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (60,'Hareoli',10);
INSERT INTO m_village(id, village_name, state_id) values (61,'Hasan Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (62,'Hiranki',10);
INSERT INTO m_village(id, village_name, state_id) values (63,'Holambi Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (64,'Holambi Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (65,'Ibrahim Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (66,'Iradat Nagar alias Naya Bans',10);
INSERT INTO m_village(id, village_name, state_id) values (67,'Isa Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (68,'Jaffar Pur Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (69,'Jagat Pur ilaqa Delhi',10);
INSERT INTO m_village(id, village_name, state_id) values (70,'Jait Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (71,'Jat Khor',10);
INSERT INTO m_village(id, village_name, state_id) values (72,'Jhangola',10);
INSERT INTO m_village(id, village_name, state_id) values (73,'Jharoda Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (74,'Jhatikra',10);
INSERT INTO m_village(id, village_name, state_id) values (75,'Jhuljhuli',10);
INSERT INTO m_village(id, village_name, state_id) values (76,'Jona Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (77,'Jonti',10);
INSERT INTO m_village(id, village_name, state_id) values (78,'Kair',10);
INSERT INTO m_village(id, village_name, state_id) values (79,'Kamal Pur Majra Burari',10);
INSERT INTO m_village(id, village_name, state_id) values (80,'Kangan Heri',10);
INSERT INTO m_village(id, village_name, state_id) values (81,'Kanjhawala',10);
INSERT INTO m_village(id, village_name, state_id) values (82,'Kankar Khera',10);
INSERT INTO m_village(id, village_name, state_id) values (83,'Kapas Hera',10);
INSERT INTO m_village(id, village_name, state_id) values (84,'Karala',10);
INSERT INTO m_village(id, village_name, state_id) values (85,'Katewara',10);
INSERT INTO m_village(id, village_name, state_id) values (86,'Kham Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (87,'Khan Pur Dhani',10);
INSERT INTO m_village(id, village_name, state_id) values (88,'Khan Pur DhaniDayal Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (89,'Khan Pur DhaniGokal Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (90,'Khan Pur DhaniJiwan Pur alias Johri Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (91,'Khan Pur DhaniKarawal Nagar',10);
INSERT INTO m_village(id, village_name, state_id) values (92,'Khan Pur DhaniKhajoori Khas',10);
INSERT INTO m_village(id, village_name, state_id) values (93,'Khan Pur DhaniMir Pur Turk',10);
INSERT INTO m_village(id, village_name, state_id) values (94,'Khan Pur DhaniMustafabad',10);
INSERT INTO m_village(id, village_name, state_id) values (95,'Khan Pur DhaniSadat Pur Gujran',10);
INSERT INTO m_village(id, village_name, state_id) values (96,'Khan Pur DhaniZiauddin Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (97,'Kharkhari Jatmal',10);
INSERT INTO m_village(id, village_name, state_id) values (98,'Kharkhari Nahar',10);
INSERT INTO m_village(id, village_name, state_id) values (99,'Kharkhari Rond',10);
INSERT INTO m_village(id, village_name, state_id) values (100,'Khera',10);
INSERT INTO m_village(id, village_name, state_id) values (101,'Khera Dabar',10);
INSERT INTO m_village(id, village_name, state_id) values (102,'Khera Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (103,'Khera Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (104,'Kirari Suleman Nagar',10);
INSERT INTO m_village(id, village_name, state_id) values (105,'Kondli',10);
INSERT INTO m_village(id, village_name, state_id) values (106,'Kotla Mahigiran',10);
INSERT INTO m_village(id, village_name, state_id) values (107,'Kureni',10);
INSERT INTO m_village(id, village_name, state_id) values (108,'Kusum Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (109,'Lad Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (110,'Lam Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (111,'Libas Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (112,'Madan Pur Dabas',10);
INSERT INTO m_village(id, village_name, state_id) values (113,'Maidan Garhi',10);
INSERT INTO m_village(id, village_name, state_id) values (114,'Malik Pur Kohi alias Rang Puri',10);
INSERT INTO m_village(id, village_name, state_id) values (115,'Malik Pur zer-Najafgarh',10);
INSERT INTO m_village(id, village_name, state_id) values (116,'Mamoor Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (117,'Mandi',10);
INSERT INTO m_village(id, village_name, state_id) values (118,'Mithe Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (119,'Mitraon',10);
INSERT INTO m_village(id, village_name, state_id) values (120,'Mohammad Pur Majri',10);
INSERT INTO m_village(id, village_name, state_id) values (121,'Mohd. Pur Ramzan Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (122,'Molar Band',10);
INSERT INTO m_village(id, village_name, state_id) values (123,'Moradabad Pahari',10);
INSERT INTO m_village(id, village_name, state_id) values (124,'Mubarak Pur Dabas',10);
INSERT INTO m_village(id, village_name, state_id) values (125,'Mukand Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (126,'Mukhmel Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (127,'Mundhela Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (128,'Mundhela Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (129,'Mungesh Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (130,'Nanak Heri',10);
INSERT INTO m_village(id, village_name, state_id) values (131,'Nangal Dewat',10);
INSERT INTO m_village(id, village_name, state_id) values (132,'Nangli Poona',10);
INSERT INTO m_village(id, village_name, state_id) values (133,'Nangli Sakrawati',10);
INSERT INTO m_village(id, village_name, state_id) values (134,'Neb Sarai',10);
INSERT INTO m_village(id, village_name, state_id) values (135,'Nithari',10);
INSERT INTO m_village(id, village_name, state_id) values (136,'Nizam Pur Rashid Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (137,'Ochandi',10);
INSERT INTO m_village(id, village_name, state_id) values (138,'Palla',10);
INSERT INTO m_village(id, village_name, state_id) values (139,'Pansali',10);
INSERT INTO m_village(id, village_name, state_id) values (140,'Paprawat',10);
INSERT INTO m_village(id, village_name, state_id) values (141,'Pehlad Pur Bangar',10);
INSERT INTO m_village(id, village_name, state_id) values (142,'Pindwala Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (143,'Pindwala Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (144,'Pooth Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (145,'Pooth Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (146,'Pul Pehlad',10);
INSERT INTO m_village(id, village_name, state_id) values (147,'Punjab Khor',10);
INSERT INTO m_village(id, village_name, state_id) values (148,'Pur Delhi',10);
INSERT INTO m_village(id, village_name, state_id) values (149,'Pur Shahdara',10);
INSERT INTO m_village(id, village_name, state_id) values (150,'Qadi Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (151,'Qazi Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (152,'Qullak Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (153,'Qutab Garh',10);
INSERT INTO m_village(id, village_name, state_id) values (154,'Qutab Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (155,'Raghu Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (156,'Raj Pur Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (157,'Rajokri',10);
INSERT INTO m_village(id, village_name, state_id) values (158,'Rani Khera',10);
INSERT INTO m_village(id, village_name, state_id) values (159,'Raota',10);
INSERT INTO m_village(id, village_name, state_id) values (160,'Rasool Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (161,'Rewla Kham Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (162,'Roshan Pura alias Dichaon Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (163,'Saba Pur Delhi',10);
INSERT INTO m_village(id, village_name, state_id) values (164,'Saba Pur Shahdara',10);
INSERT INTO m_village(id, village_name, state_id) values (165,'Sahibabad Daulat Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (166,'Saidabad',10);
INSERT INTO m_village(id, village_name, state_id) values (167,'Saidul Azaib',10);
INSERT INTO m_village(id, village_name, state_id) values (168,'Salah Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (169,'Salah Pur Majra',10);
INSERT INTO m_village(id, village_name, state_id) values (170,'Salem Pur Majra Burari',10);
INSERT INTO m_village(id, village_name, state_id) values (171,'Samas Pur Khalsa',10);
INSERT INTO m_village(id, village_name, state_id) values (172,'Sambhalka',10);
INSERT INTO m_village(id, village_name, state_id) values (173,'Saoda',10);
INSERT INTO m_village(id, village_name, state_id) values (174,'Sarang Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (175,'Satberi',10);
INSERT INTO m_village(id, village_name, state_id) values (176,'Shah Pur Garhi',10);
INSERT INTO m_village(id, village_name, state_id) values (177,'Shahur Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (178,'Shakar Pur Baramad',10);
INSERT INTO m_village(id, village_name, state_id) values (179,'Shamas Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (180,'Sher Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (181,'Sher Pur Deri',10);
INSERT INTO m_village(id, village_name, state_id) values (182,'Shikar Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (183,'Singhola',10);
INSERT INTO m_village(id, village_name, state_id) values (184,'Singhu',10);
INSERT INTO m_village(id, village_name, state_id) values (185,'Siras Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (186,'Sultan Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (187,'Sultan Pur Dabas',10);
INSERT INTO m_village(id, village_name, state_id) values (188,'Sultan Pur Majra',10);
INSERT INTO m_village(id, village_name, state_id) values (189,'Sunger Pur Delhi',10);
INSERT INTO m_village(id, village_name, state_id) values (190,'Surakh Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (191,'Surera',10);
INSERT INTO m_village(id, village_name, state_id) values (192,'Taj Pul',10);
INSERT INTO m_village(id, village_name, state_id) values (193,'Taj Pur Kalan',10);
INSERT INTO m_village(id, village_name, state_id) values (194,'Taj Pur Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (195,'Tigi Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (196,'Tigri',10);
INSERT INTO m_village(id, village_name, state_id) values (197,'Tikri Khurd',10);
INSERT INTO m_village(id, village_name, state_id) values (198,'Tukhmir Pur',10);
INSERT INTO m_village(id, village_name, state_id) values (199,'Ujwa',10);
INSERT INTO m_village(id, village_name, state_id) values (200,'Zind Pur',10);


COMMIT;
